### ISSUE TITLE
Revit SkiaSharp exception on close

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#1192]
Steps to repro:
- launch revit
- open dui
- close revit
- wait without stopping the debugger

Not sure how to properly catch/avoid it.

```
System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>DefaultDomain</AppDomain><Exception><ExceptionType>System.AccessViolationException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Attempted to read or write protected memory. This is often an indication that other memory is corrupt.</Message><StackTrace>   at SkiaSharp.Internals.PlatformLock.NonAlertableWin32Lock.EnterCriticalSection(IntPtr lpCriticalSection)
   at SkiaSharp.Internals.PlatformLock.NonAlertableWin32Lock.EnterWriteLock()
   at SkiaSharp.HandleDictionary.DeregisterHandle(IntPtr handle, SKObject instance)
   at SkiaSharp.SKObject.DeregisterHandle(IntPtr handle, SKObject instance)
   at SkiaSharp.SKObject.set_Handle(IntPtr value)
   at SkiaSharp.SKNativeObject.Dispose(Boolean disposing)
   at SkiaSharp.SKImage.Dispose(Boolean disposing)
   at SkiaSharp.SKNativeObject.Finalize()</StackTrace><ExceptionString>System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at SkiaSharp.Internals.PlatformLock.NonAlertableWin32Lock.EnterCriticalSection(IntPtr lpCriticalSection)
   at SkiaSharp.Internals.PlatformLock.NonAlertableWin32Lock.EnterWriteLock()
   at SkiaSharp.HandleDictionary.DeregisterHandle(IntPtr handle, SKObject instance)
   at SkiaSharp.SKObject.DeregisterHandle(IntPtr handle, SKObject instance)
   at SkiaSharp.SKObject.set_Handle(IntPtr value)
   at SkiaSharp.SKNativeObject.Dispose(Boolean disposing)
   at SkiaSharp.SKImage.Dispose(Boolean disposing)
   at SkiaSharp.SKNativeObject.Finalize()</ExceptionString></Exception></TraceRecord>
An unhandled exception of type 'System.AccessViolationException' occurred in SkiaSharp.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

```

**Comment by teocomi** [comment]
So this should be fixed now, my findings here for posterity:
- we are using Avalonia's [manual lifetime management](https://github.com/AvaloniaUI/Avalonia/wiki/Application-lifetimes) because the connectors are plugins and not standalone applications
- the `app.Run(cts.Token);` method helps with manual lifetime management but it is UI blocking 
- if we put it inside a `Task.Run()` it basically has no effect as the Avalonia main loop is running in a separate thread, so it's like we don't call it at all and then Revit crashes on shutdown
- by calling `app.Run(cts.Token);` and immediately stopping it, seems that the app is initialized fine and no errors are thrown by Revit on shutdown:

```
        var cts = new CancellationTokenSource();
        cts.CancelAfter(100);
        AvaloniaApp.Run(cts.Token);
```
