### ISSUE TITLE
Revit: Units issue when receiving direct shape

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sharp#336]
These stairs were sent from revit, but can't be received again.

the commit:
https://speckle.xyz/streams/7b9d61b472/commits/9e7731f7ac

the error:

```
The current Unit System is unsupported.
   at Objects.Converter.Revit.ConverterRevit.UnitsToNative(String units)
   at Objects.Converter.Revit.ConverterRevit.PointToNative(Point pt)
   at Objects.Converter.Revit.ConverterRevit.ArrayToPoints(IEnumerable`1 arr, String units)
   at Objects.Converter.Revit.ConverterRevit.MeshToNative(Mesh mesh)
   at Objects.Converter.Revit.ConverterRevit.DirectShapeToNative(Mesh mesh, BuiltInCategory cat)
   at Speckle.ConnectorRevit.UI.ConnectorBindingsRevit.ConvertReceivedObjects(List`1 objects, ISpeckleConverter converter, StreamState state) in C:\Users\circleci\project\ConnectorRevit\ConnectorRevit\UI\ConnectorBindingsRevit.Receive.cs:line 181

Object reference not set to an instance of an object.
   at Objects.Converter.Revit.ConverterRevit.RailingToNative(RevitRailing speckleRailing)
   at Speckle.ConnectorRevit.UI.ConnectorBindingsRevit.ConvertReceivedObjects(List`1 objects, ISpeckleConverter converter, StreamState state) in C:\Users\circleci\project\ConnectorRevit\ConnectorRevit\UI\ConnectorBindingsRevit.Receive.cs:line 181
```

**Comment by AlanRynne** [comment]
I've been looking into it and I think I have the issue located.

Turns out that in the case of the `Stair` class, when we create the `displayMesh` we fail to assign the units to it.
This goes unnoticed until you receive that mesh in Revit once again.

The unit `null` value get's propagated to all the vertices of the mesh and throws an error on `PointToNative` as the points will have no units either.

I would do:

- Ensure all geometric elements have units assigned on conversion `ToSpeckle`.
- In `ToNative` operations, if the units of an object are null, try get the parent's units.

This will give us double assurance that everything is being scaled appropriately.
