### ISSUE TITLE
Revit: Issues sending model curves and detail curves

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sharp#339]
no errors or warnings appear, but the result is incorrect

the commit:
https://latest.speckle.dev/streams/0c6ad366c4/commits/e30e7ad93c

in revit:

![image](https://user-images.githubusercontent.com/7717434/111144383-ea682780-857e-11eb-895c-08b1f6c9dce3.png)

in viewer:

![image](https://user-images.githubusercontent.com/7717434/111144408-f227cc00-857e-11eb-88d7-184a3d41704a.png)

**Comment by izzylys** [comment]
Receiving the Rhino Standard Geometry test file does produce errors upon receiving:

```
The input curve is not bound.
Parameter name: curve
   at Autodesk.Revit.CurveAPIUtils.GetCurveEndpoint(Curve curve, Int32 index)
   at Objects.Converter.Revit.ConverterRevit.NewSketchPlaneFromCurve(Curve curve)
   at Objects.Converter.Revit.ConverterRevit.ModelCurveToNative(ICurve speckleLine)
   at Speckle.ConnectorRevit.UI.ConnectorBindingsRevit.ConvertReceivedObjects(List`1 objects, ISpeckleConverter converter, StreamState state) in C:\\Users\\circleci\\project\\ConnectorRevit\\ConnectorRevit\\UI\\ConnectorBindingsRevit.Receive.cs:line 181

Curve must be in the plane
Parameter name: pCurveCopy
   at ?A0x1ba248f9.newModelCurveInternal(ADocument* pADoc, Sketch* pSketch, ElementId sketchPlaneId, GCurve* pCurveCopy)
   at Autodesk.Revit.Creation.ItemFactoryBase.NewModelCurve(Curve geometryCurve, SketchPlane sketchPlane)
   at Objects.Converter.Revit.ConverterRevit.ModelCurveToNative(ICurve speckleLine)
   at Speckle.ConnectorRevit.UI.ConnectorBindingsRevit.ConvertReceivedObjects(List`1 objects, ISpeckleConverter converter, StreamState state) in C:\\Users\\circleci\\project\\ConnectorRevit\\ConnectorRevit\\UI\\ConnectorBindingsRevit.Receive.cs:line 181
```

**Comment by AlanRynne** [comment]
`GetCurveEnpoint` is only supposed to be used on `bounded` curves. In Revit, if a `Curve` is **unbounded**, it has no start or end point (thanks Autodesk... 🤕 ). We could do one of several things here:

- Bound every incoming curve (seems rather overkill and not sure of other ramifications of this decision).
- Check for `isBounded` and use `Evaluate(t)` when Curve is unbounded. Usually these unbounded curves have determined domains. Ellipse, circle have 0-2PI.

Some notes on Revit curves here: https://knowledge.autodesk.com/support/revit-products/learn-explore/caas/CloudHelp/cloudhelp/2014/ENU/Revit/files/GUID-AB7DD330-5FCA-47B3-BAC3-0E0658164FE8-htm.html
