### ISSUE TITLE
Pushing Civil 3D Corridor shows an error

### ISSUE THREAD

**Issue by jhdempsey86** [specklesystems/speckle-sharp#3516]
## Prerequisites

- [X ] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [X ] I checked the [documentation](https://speckle.guide/) and found no answer.
- [X ] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [X ] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [X ] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

Civil 3D Connector

## Describe the bug

A simple Civil 3D Corridor is failing to push to Speckle.
It shows an error when just the corridor object is selected to be pushed (first screenshot)

If you select everything to be pushed, it shows a success message, but everything except the Corridor has been pushed
The corridor is on layer "C-ROAD-CORR" (see second screenshot)
But this layer is not visible when you view the latest commit online (third screenshot)

## To Reproduce

In the Speckle connector, choose your
For the objects to send, choose the "Selection" setting
Select the corridor in the model, then click "

See this video recording of the process

https://github.com/specklesystems/speckle-sharp/assets/67244422/900f4962-68cc-47de-baf9-33d0536e60c9

## Expected behavior

The corridor should upload to Speckle

## Screenshots

![image](https://github.com/specklesystems/speckle-sharp/assets/67244422/faf8593a-cb02-4362-9b29-74abe3cceb38)

![image](https://github.com/specklesystems/speckle-sharp/assets/67244422/7f030101-9ab8-4d82-9235-b8fd0e81fba1)

![image](https://github.com/specklesystems/speckle-sharp/assets/67244422/5278e1a5-cb78-4e3a-8de5-ea8cd3379e9a)

## System Info

If applicable, please fill in the below details - they help a lot!

### Desktop (please complete the following information):

Speckle Civil 3D Connector v 2.20.0-wip2
Civil 3D 2024.3
Windows 11 Enterprise

## Failure Logs

From %appdata%\Speckle\Logs\civil3dCivil 3D 2024\SpeckleCoreLog20240617.txt

```
2024-06-17 12:13:15.727 +01:00 [ERR] SendCommand failed - Zero objects converted successfully. Send stopped.
Speckle.Core.Logging.SpeckleException: Zero objects converted successfully. Send stopped.
   at Speckle.ConnectorAutocadCivil.UI.ConnectorBindingsAutocad.<SendStream>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DesktopUI2.ViewModels.StreamViewModel.<SendCommand>d__215.MoveNext()

```
-->

## Additional context

Drawign which produces the error is attached here.

The drwaing is a simple corridor using one of Civil 3D's built in subassemblies

[Drawing1.zip](https://github.com/user-attachments/files/15866160/Drawing1.zip)

## Proposed Solution (if any)

None

#### Optional: Affected Projects

None

**Comment by jhdempsey86** [comment]
This issue should now be resolved with the code changes in #3578
There is an issue with the Excel connector not being able to view any models which have been pushed using the code changes that have been made. A new bug report has been made for this
