### ISSUE TITLE
Revit: failing xUnit tests

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sharp#496]
**Test Info**

Connector: Revit
Test Case: xUnit
Test stream link: N/A

**Report**

- [x]  columns
```console
Assert.Empty() Failure
Collection: [System.Exception: The input familyInstance is not of a structural framing category.
Parameter name: familyInstance ---> Autodesk.Revit.Exceptions.ArgumentsInconsistentException: The input familyInstance is not of a structural framing category.
Parameter name: familyInstance
   at Autodesk.Revit.DB.Structure.StructuralFramingUtils.DisallowJoinAtEnd(FamilyInstance familyInstance, Int32 end)
   at Objects.Converter.Revit.ConverterRevit.ColumnToNative(Column speckleColumn)
   at ConverterRevitTests.SpeckleConversionTest.<>c__DisplayClass3_0`1.<SpeckleToNative>b__4() in C:\Users\izzy lyseggen\Documents\dev\next\sharp\Objects\Converters\ConverterRevit\ConverterRevitTests\SpeckleConversionTest.cs:line 99
   --- End of inner exception stack trace ---]

   at Xunit.Assert.Empty(IEnumerable collection)
   at ConverterRevitTests.SpeckleConversionTest.SpeckleToNative[T](Action`2 assert, UpdateData ud) in C:\Users\izzy lyseggen\Documents\dev\next\sharp\Objects\Converters\ConverterRevit\ConverterRevitTests\SpeckleConversionTest.cs:line 121
   at ConverterRevitTests.ColumnTests.ColumnToNative() in C:\Users\izzy lyseggen\Documents\dev\next\sharp\Objects\Converters\ConverterRevit\ConverterRevitTests\ColumnTests.cs:line 41
```
- [x] walls
```console
Assert.Empty() Failure
Collection: [System.Exception: The input familyInstance is not of a structural framing category.
Parameter name: familyInstance ---> Autodesk.Revit.Exceptions.ArgumentsInconsistentException: The input familyInstance is not of a structural framing category.
Parameter name: familyInstance
   at Autodesk.Revit.DB.Structure.StructuralFramingUtils.DisallowJoinAtEnd(FamilyInstance familyInstance, Int32 end)
   at Objects.Converter.Revit.ConverterRevit.ColumnToNative(Column speckleColumn)
   at ConverterRevitTests.SpeckleConversionTest.<>c__DisplayClass3_0`1.<SpeckleToNative>b__4() in C:\Users\izzy lyseggen\Documents\dev\next\sharp\Objects\Converters\ConverterRevit\ConverterRevitTests\SpeckleConversionTest.cs:line 99
   --- End of inner exception stack trace ---]

   at Xunit.Assert.Empty(IEnumerable collection)
   at ConverterRevitTests.SpeckleConversionTest.SpeckleToNative[T](Action`2 assert, UpdateData ud) in C:\Users\izzy lyseggen\Documents\dev\next\sharp\Objects\Converters\ConverterRevit\ConverterRevitTests\SpeckleConversionTest.cs:line 121
   at ConverterRevitTests.SpeckleConversionTest.SpeckleToNativeUpdates[T](Action`2 assert) in C:\Users\izzy lyseggen\Documents\dev\next\sharp\Objects\Converters\ConverterRevit\ConverterRevitTests\SpeckleConversionTest.cs:line 140
   at ConverterRevitTests.ColumnTests.WallToNativeUpdates() in C:\Users\izzy lyseggen\Documents\dev\next\sharp\Objects\Converters\ConverterRevit\ConverterRevitTests\ColumnTests.cs:line 48

Assert.Empty() Failure
Collection: [System.Exception: Skipping not supported type: Base, System.Exception: Skipping not supported type: Base]

   at Xunit.Assert.Empty(IEnumerable collection)
   at ConverterRevitTests.SpeckleConversionTest.SpeckleToNative[T](Action`2 assert, UpdateData ud) in C:\Users\izzy lyseggen\Documents\dev\next\sharp\Objects\Converters\ConverterRevit\ConverterRevitTests\SpeckleConversionTest.cs:line 121
   at ConverterRevitTests.WallTests.WallToNative() in C:\Users\izzy lyseggen\Documents\dev\next\sharp\Objects\Converters\ConverterRevit\ConverterRevitTests\WallTests.cs:line 43
```
- [x] openings
```console
Assert.Equal() Failure
Expected: 46.6214 (rounded from 46.6214280007989)
Actual:   14210.2113 (rounded from 14210.2112546435)

   at Xunit.Assert.Equal(Double expected, Double actual, Int32 precision)
   at ConverterRevitTests.SpeckleConversionTest.AssertEqualParam(Element expected, Element actual, BuiltInParameter param) in C:\Users\izzy lyseggen\Documents\dev\next\sharp\Objects\Converters\ConverterRevit\ConverterRevitTests\SpeckleConversionTest.cs:line 234
   at ConverterRevitTests.OpeningTests.AssertOpeningEqual(Element sourceElem, Element destElem) in C:\Users\izzy lyseggen\Documents\dev\next\sharp\Objects\Converters\ConverterRevit\ConverterRevitTests\OpeningTests.cs:line 73
   at ConverterRevitTests.SpeckleConversionTest.SpeckleToNative[T](Action`2 assert, UpdateData ud) in C:\Users\izzy lyseggen\Documents\dev\next\sharp\Objects\Converters\ConverterRevit\ConverterRevitTests\SpeckleConversionTest.cs:line 127
   at ConverterRevitTests.OpeningTests.OpeningToNative() in C:\Users\izzy lyseggen\Documents\dev\next\sharp\Objects\Converters\ConverterRevit\ConverterRevitTests\OpeningTests.cs:line 53
```
- [ ] breps
not sure if this is still up to date, but here are some examples
```console
>>> BREP SELECTION TO NATIVE
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at ConverterRevitTests.BrepTests.BrepSelectionToNative() in C:\Users\izzy lyseggen\Documents\dev\next\sharp\Objects\Converters\ConverterRevit\ConverterRevitTests\BrepTests.cs:line 84

One or more errors occurred.

>>> BREP BOAT
Object reference not set to an instance of an object.

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ConverterRevitTests.BrepTests.BrepToNative(String fileName) in C:\Users\izzy lyseggen\Documents\dev\next\sharp\Objects\Converters\ConverterRevit\ConverterRevitTests\BrepTests.cs:line 61

   at Objects.Converter.Revit.ConverterRevit.MeshToNative(Mesh mesh, TessellatedShapeBuilderTarget target, TessellatedShapeBuilderFallback fallback)
   at Objects.Converter.Revit.ConverterRevit.BrepToDirectShape(Brep brep, BuiltInCategory cat)
   at ConverterRevitTests.BrepTests.<>c__DisplayClass2_0.<BrepToNative>b__0() in C:\Users\izzy lyseggen\Documents\dev\next\sharp\Objects\Converters\ConverterRevit\ConverterRevitTests\BrepTests.cs:line 64
   at xUnitRevitUtils.xru.<>c__DisplayClass20_0.<RunInTransaction>b__0()

>>> BREP COMPLEX
Assert.True() Failure
Expected: True
Actual:   False

   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
   at ConverterRevitTests.BrepTests.BrepToNative(String fileName) in C:\Users\izzy lyseggen\Documents\dev\next\sharp\Objects\Converters\ConverterRevit\ConverterRevitTests\BrepTests.cs:line 67
```

**Comment by teocomi** [comment]
1 and 2 might be non-issues or just something going on with the family selection
3 is just a rounding issue
4 I think the breps tests where never actually updated by @AlanRynne with the newest brep structure

**Comment by AlanRynne** [comment]
Breps where updated, but the `Boat` and `Plane` models have some complex Brep features that revit we never got revit to handle properly. Though it looks like there's several things going on:

- Seems like "Selection to native" is failing because there's nothing selected. Not sure if i missed some setup there.
- Boat is failing because it does not have a `displayMesh`? 🤔  this should never happen.
- `Complex` is behaving as expected (you'll get the mesh representation in the document, but since what you're actually expecting is a Brep, it fails). We could change it to expect a mesh to have it passing?
