### ISSUE TITLE
Failing Tests: Wall and Opening 

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sharp#84]
`WallTests.WallToNative` failing bc it can't create a wall

```
The referenced object is not valid, possibly because it has been deleted from the database, or its creation was undone.

   at Autodesk.Revit.DB.Element.get_Parameter(BuiltInParameter parameterId)
   at SpeckleRevitTests.SpeckleConversionTest.AssertEqualParam(Element expected, Element actual, BuiltInParameter param) in C:\Users\izzy lyseggen\Documents\dev\next\ConverterRevit\SpeckleRevitTests\SpeckleConversionTest.cs:line 137
   at SpeckleRevitTests.WallTests.AssertWallEqual(Wall sourceElem, Wall destElem) in C:\Users\izzy lyseggen\Documents\dev\next\ConverterRevit\SpeckleRevitTests\WallTests.cs:line 59
   at SpeckleRevitTests.SpeckleConversionTest.SpeckleToNative[T](Action`2 assert) in C:\Users\izzy lyseggen\Documents\dev\next\ConverterRevit\SpeckleRevitTests\SpeckleConversionTest.cs:line 67
   at SpeckleRevitTests.WallTests.WallToNative() in C:\Users\izzy lyseggen\Documents\dev\next\ConverterRevit\SpeckleRevitTests\WallTests.cs:line 42
```

`OpeningTests.OpeningToNative` failing bc the opening is not going through anything

```
One or more errors occurred.

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at SpeckleRevitTests.SpeckleConversionTest.SpeckleToNative[T](Action`2 assert) in C:\Users\izzy lyseggen\Documents\dev\next\ConverterRevit\SpeckleRevitTests\SpeckleConversionTest.cs:line 56
   at SpeckleRevitTests.OpeningTests.OpeningToNative() in C:\Users\izzy lyseggen\Documents\dev\next\ConverterRevit\SpeckleRevitTests\OpeningTests.cs:line 60
```

**Comment by teocomi** [comment]
Walls are failing because of #110 10
While the opening is just showing a warning, but it does create them. Will close this for now!
